name: next-backend-services

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=drowssap
      - POSTGRES_DB=platform
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 1s
        timeout: 5s
        retries: 10

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:8
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=root@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - postgres
  #   restart: always
